---
title: "Untitled"
author: "wilfried"
date: "2024-12-08"
output: html_document
---
# Load libraries
```{r}
#install.packages("blogdown")
#blogdown::new_site()
library(blogdown)
library(tidyverse)
library(sf)
library(terra)
library(mapview)
library(geoR)
library(gstat)
library(spData)
library(tmap)
library(sp)
library(viridis)
```

```{r}
data(meuse)
data(meuse.grid)
meuse <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992)
meuse.grid <- st_as_sf(meuse.grid, coords = c("x", "y"),
                       crs = 28992)
```

# Kriging
## Anisotropy testing
```{r}
# Compute directional variograms
v_dir <- variogram(log(zinc) ~ 1, meuse, alpha = c(0, 45, 90, 135))

# Plot the directional variograms
plot(v_dir)
```

## Define anisotropic variogram model
```{r}
# Define anisotropic variogram model
anisotropic_model <- vgm(psill = 0.8, model = "Sph", range = 1000, nugget = 0.1,
                         anis = c(45, 0.6))  # 45° major axis, anisotropy ratio 0.6
v <- variogram(log(zinc) ~ 1, data = meuse)
plot(v)
# Fit the anisotropic variogram model
anisotropic_fitted <- fit.variogram(v, model = anisotropic_model)

# Plot the fitted anisotropic variogram
plot(v, anisotropic_fitted, cutoff = 1500, cex = 1.5)
```

## kriging
```{r}
k <- gstat(formula = log(zinc) ~ 1, data = meuse, model = anisotropic_model)
kpred <- predict(k, meuse.grid)
```

```{r}
# Perform cross-validation
cv <- krige.cv(log(zinc) ~ 1, locations = meuse, model = anisotropic_fitted)

# Extract observed and predicted values
observed <- cv$observed
predicted <- cv$var1.pred

```

```{r}
# Calculate R-squared
r2 <- 1 - (sum((observed - predicted)^2) / sum((observed - mean(observed))^2))

# Display R-squared
cat("R-squared:", r2, "\n")
```

```{r}
# Calculate RMSE
rmse <- sqrt(mean((observed - predicted)^2))
cat("RMSE:", rmse, "\n")
```

```{r}
# Calculate MAE
mae <- mean(abs(observed - predicted))
cat("MAE:", mae, "\n")
```

```{r}
# Extract coordinates
kpred_coords <- cbind(kpred, st_coordinates(kpred))

# Check the structure of the new data
head(kpred_coords)
```

```{r}
custom_levels <- c(4, 6, 7, 7.5)
custom_labels <- c("2 lbs/ac", "4 lbs/ac", "6 lbs/ac")
ggplot() + geom_sf(data = kpred, aes(color = var1.pred),
                   show.legend = FALSE) +
  geom_sf(data = meuse) +
  geom_contour_filled(data = kpred, aes(x = kpred_coords$X, y = kpred_coords$Y, z = var1.pred), #color = "gray100",
              # bins = 4
              breaks = custom_levels
               ) +
  scale_fill_viridis_d(labels = custom_labels) +  
  scale_fill_manual(values = c("green4", "red4", "yellow"))+
  labs(x = "Longitude", y = "Latitude", fill = "Zinc Prescription (lbs/ac)")+
  theme_bw()
```
